import { transactionLock, type LockService } from '../src/web/transaction-lock.ts';
import test from 'node:test';
import assert from 'node:assert/strict';
import { createCommitController, type CommitDependencies, type PendingRecord } from '../src/web/transaction.ts';
import { Phase, pureCircuits, type Ledger } from '../managed/cat-bluff/contract/index.js';
const secret = new Uint8Array(32).fill(7), salt = new Uint8Array(32).fill(9), context = new Uint8Array(32).fill(1);
const player = pureCircuits.deriveRole(context, 1n, secret);
const commitment = pureCircuits.deriveCard(context, 1n, player, 7n, salt);
const hex = (x:Uint8Array) => Buffer.from(x).toString('hex');
function fixture() {
 let record:PendingRecord|null=null, submitCount=0, guard=true;
 const ledger:Ledger={gameContext:context,round:1n,phase:Phase.Empty,player,challenger:new Uint8Array(32),commitment:new Uint8Array(32),claimedRank:0n,revealedRank:0n,truthful:false};
 const held=new Set<string>();
 const service:LockService={request:async (name,_options,callback)=>{if(held.has(name))return callback(null);held.add(name);try{return await callback({name,mode:'exclusive'});}finally{held.delete(name);}}};
 const deps:CommitDependencies={withLock:transactionLock(service),read:async()=>ledger,readAt:async()=>({...ledger,phase:Phase.Committed,claimedRank:7n,commitment}),watch:async()=>({status:'SucceedEntirely',txHash:'b'.repeat(64),blockHeight:10}),execute:async hooks=>{await hooks.beforeProof();await hooks.beforeApproval();await hooks.beforeSubmit('a'.repeat(64));submitCount++;},timeoutMs:10};
 const store={get:()=>record,set:(x:PendingRecord|null)=>{record=x;}};
 const input={config:{network:'preprod' as const,contractAddress:'c'.repeat(64),indexer:'https://example.com/',indexerWS:'wss://example.com/',substrateNode:'https://example.com/',proverServer:'http://127.0.0.1:6300'},opened:{scope:{network:'preprod' as const,contractAddress:'c'.repeat(64),context:hex(context),round:'1' as const},state:{secret,rank:7n,salt}},claim:7n,guard:async()=>{if(!guard)throw Error('private secret');},store,onStage:()=>{}};
 return {deps,input,controller:createCommitController(deps),ledger,store,get submits(){return submitCount;},disconnect:()=>{guard=false;}};
}
test('mocked external adapters: receipt requires successful status and matching block state',async()=>{const f=fixture();const result=await f.controller.run(f.input);assert.equal(result.status,'confirmed');assert.equal(f.store.get(),null);assert.equal(f.submits,1);});
test('wrong phase never submits',async()=>{const f=fixture();Object.assign(f.ledger,{phase:Phase.Committed});await assert.rejects(f.controller.run(f.input),/empty/i);assert.equal(f.submits,0);});
test('duplicate entry cannot begin another transaction',async()=>{const f=fixture();f.deps.read=()=>new Promise(()=>{});const first=f.controller.run(f.input);void first;await assert.rejects(f.controller.run(f.input),/already/i);});
test('disconnect after proof prevents approval and submit',async()=>{const f=fixture();f.deps.execute=async h=>{await h.beforeProof();f.disconnect();await h.beforeApproval();};await assert.rejects(f.controller.run(f.input),/could not/i);assert.equal(f.submits,0);});
test('proof failure sanitizes errors and leaves no pending transaction',async()=>{const f=fixture();f.deps.execute=async h=>{await h.beforeProof();throw Error('secret salt');};await assert.rejects(f.controller.run(f.input),/^Error: Transaction could not be completed\.$/);assert.equal(f.store.get(),null);});
test('uncertain submit retains public record and never resubmits on retry',async()=>{const f=fixture();f.deps.execute=async h=>{await h.beforeSubmit('a'.repeat(64));throw Error('node disconnected secret');};f.deps.watch=()=>new Promise(()=>{});assert.equal((await f.controller.run(f.input)).status,'pending');assert.equal(f.store.get()?.submission,'uncertain');await assert.rejects(f.controller.run(f.input),/pending/i);assert.equal(JSON.stringify(f.store.get()).includes('secret'),false);});
test('pending record exists before submission',async()=>{const f=fixture();f.deps.execute=async h=>{await h.beforeSubmit('a'.repeat(64));assert.equal(f.store.get()?.submission,'attempting');};await f.controller.run(f.input);});
test('timeout stays pending and refresh reconciles the same transaction without wallet',async()=>{const f=fixture();f.deps.watch=()=>new Promise(()=>{});assert.equal((await f.controller.run(f.input)).status,'pending');f.deps.watch=async()=>({status:'SucceedEntirely',txHash:'b'.repeat(64),blockHeight:10});assert.equal((await f.controller.reconcile(f.input.config,f.store))?.status,'confirmed');});
test('chain failure cannot become a successful receipt',async()=>{const f=fixture();f.deps.watch=async()=>({status:'FailEntirely',txHash:'b'.repeat(64),blockHeight:10});await assert.rejects(f.controller.run(f.input),/rejected/i);assert.ok(f.store.get());});
test('incorrect commitment at confirmation block fails receipt verification',async()=>{const f=fixture();f.deps.readAt=async()=>({...f.ledger,phase:Phase.Committed,claimedRank:7n});await assert.rejects(f.controller.run(f.input),/match/i);assert.ok(f.store.get());});

test('timeout includes reading the confirmation block',async()=>{const f=fixture();f.deps.readAt=()=>new Promise(()=>{});const result=await Promise.race([f.controller.run(f.input),new Promise<string>(r=>setTimeout(()=>r('hung'),60))]);assert.notEqual(result,'hung');assert.equal(typeof result==='object'&&result.status,'pending');});
test('two controllers sharing a browser lock cannot prove or overwrite the same contract concurrently',async()=>{const f=fixture();let release!:()=>void;f.deps.read=()=>new Promise(r=>{release=()=>r(f.ledger);});const second=createCommitController(f.deps);const first=f.controller.run(f.input);await new Promise(r=>setTimeout(r,0));await assert.rejects(Promise.race([second.run(f.input),new Promise((_,reject)=>setTimeout(()=>reject(Error('concurrent request hung')),30))]),/already|another tab/i);release();await first;assert.equal(f.submits,1);});
test('unavailable browser locks fail closed before proving',async()=>{const f=fixture();f.deps.withLock=transactionLock(undefined);await assert.rejects(f.controller.run(f.input),/Web Locks/);assert.equal(f.submits,0);});
test('pending record appearing during preparation cannot be overwritten',async()=>{const f=fixture();const foreign={network:'preprod' as const,contractAddress:f.input.config.contractAddress,txId:'d'.repeat(64),expectedCommitment:'e'.repeat(64),claim:'8',timestamp:123,submission:'uncertain' as const};f.deps.execute=async h=>{f.store.set(foreign);await h.beforeSubmit('a'.repeat(64));};await assert.rejects(f.controller.run(f.input),/pending/i);assert.deepEqual(f.store.get(),foreign);});
test('foreign pending record cannot be updated after submission or cleared by reconciliation',async()=>{const f=fixture();const foreign={network:'preprod' as const,contractAddress:f.input.config.contractAddress,txId:'d'.repeat(64),expectedCommitment:'e'.repeat(64),claim:'8',timestamp:123,submission:'uncertain' as const};f.deps.execute=async h=>{await h.beforeSubmit('a'.repeat(64));f.store.set(foreign);};await assert.rejects(f.controller.run(f.input),/changed/i);assert.deepEqual(f.store.get(),foreign);});
test('reconciliation refuses to clear a replacement pending record',async()=>{const f=fixture();f.deps.readAt=async()=>{f.store.set({...f.store.get()!,txId:'d'.repeat(64)});return {...f.ledger,phase:Phase.Committed,claimedRank:7n,commitment};};await assert.rejects(f.controller.run(f.input),/changed/i);assert.equal(f.store.get()?.txId,'d'.repeat(64));});
test('known cancellation before wallet invocation clears only its own pending record',async()=>{const f=fixture();f.deps.execute=async h=>{const id='a'.repeat(64);await h.beforeSubmit(id);f.disconnect();h.submissionAborted(id);throw Error('not invoked');};await assert.rejects(f.controller.run(f.input),/could not/i);assert.equal(f.store.get(),null);});
