import { act, renderHook, waitFor, cleanup } from '@testing-library/react';
import { afterEach, beforeEach, expect, test, vi } from 'vitest';
const mocks=vi.hoisted(()=>({read:vi.fn(),run:vi.fn(),reconcile:vi.fn(),decrypt:vi.fn(),validate:vi.fn(),connect:vi.fn()}));
vi.mock('../../src/web/contract.ts',()=>({readPublicState:mocks.read,runCommit:mocks.run,reconcilePending:mocks.reconcile}));
vi.mock('../../src/web/private-package.ts',()=>({decryptPackage:mocks.decrypt,validatePackageState:mocks.validate}));
vi.mock('../../src/web/wallet.ts',()=>({discoverWallets:()=>[],WalletSession:class {
 callback:(s:unknown)=>void;current=false;constructor(cb:(s:unknown)=>void){this.callback=cb;}
 async connect(){mocks.connect();this.current=true;this.callback({status:'connected',name:'Mock external wallet',address:'public-address'});}
 disconnect(){this.current=false;this.callback({status:'disconnected'});}
 async revalidate(){}
 capture(){if(!this.current)throw Error('Not connected');return {guard:async()=>{if(!this.current)throw Error('Changed');},isCurrent:()=>this.current};}
}}));
import { useMidnight } from '../../src/web/useMidnight.ts';
const receipt={network:'preprod',contractAddress:'c'.repeat(64),status:'SucceedEntirely'};
const publicState={phase:0,round:1n};
beforeEach(()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>receipt}));localStorage.clear();mocks.read.mockResolvedValue(publicState);mocks.reconcile.mockResolvedValue(null);});
afterEach(()=>{cleanup();vi.unstubAllGlobals();vi.clearAllMocks();});
test('loads verified public state without requesting wallet authorization',async()=>{const {result}=renderHook(()=>useMidnight());await waitFor(()=>expect(result.current.publicState).toEqual(publicState));expect(result.current.config?.contractAddress).toBe(receipt.contractAddress);expect(mocks.connect).not.toHaveBeenCalled();expect(result.current.privateReady).toBe(false);});
test('disconnect while decrypting wipes the late private result and cannot restore ready state',async()=>{let resolve!:(value:unknown)=>void;mocks.decrypt.mockReturnValue(new Promise(r=>{resolve=r;}));const {result}=renderHook(()=>useMidnight());await waitFor(()=>expect(result.current.config).not.toBeNull());await act(()=>result.current.connect({} as never));let importing!:Promise<void>;act(()=>{importing=result.current.importPackage('ciphertext','password');});await waitFor(()=>expect(mocks.decrypt).toHaveBeenCalled());act(()=>result.current.disconnect());const secret=new Uint8Array(32).fill(9),salt=new Uint8Array(32).fill(8);await act(async()=>{resolve({scope:{},state:{secret,salt,rank:7n}});await importing;});expect(result.current.privateReady).toBe(false);expect([...secret]).toEqual(new Array(32).fill(0));expect([...salt]).toEqual(new Array(32).fill(0));expect(mocks.run).not.toHaveBeenCalled();});
test('successful import never exposes private witnesses in returned state',async()=>{mocks.decrypt.mockResolvedValue({scope:{},state:{secret:new Uint8Array(32).fill(9),salt:new Uint8Array(32).fill(8),rank:7n}});const {result}=renderHook(()=>useMidnight());await waitFor(()=>expect(result.current.config).not.toBeNull());await act(()=>result.current.connect({} as never));await act(()=>result.current.importPackage('ciphertext','password'));expect(result.current.privateReady).toBe(true);expect('opened' in result.current).toBe(false);expect('secret' in result.current).toBe(false);act(()=>result.current.disconnect());expect(result.current.privateReady).toBe(false);});
test('corrupt pending storage blocks a new commit',async()=>{localStorage.setItem(`cat-bluff:pending:preprod:${receipt.contractAddress}`,'corrupt');const {result}=renderHook(()=>useMidnight());await waitFor(()=>expect(result.current.error).toMatch(/pending|storage/i));await act(()=>result.current.commit(7n));expect(mocks.run).not.toHaveBeenCalled();});
test('unmount wipes imported witness bytes',async()=>{const secret=new Uint8Array(32).fill(9),salt=new Uint8Array(32).fill(8);mocks.decrypt.mockResolvedValue({scope:{},state:{secret,salt,rank:7n}});const {result,unmount}=renderHook(()=>useMidnight());await waitFor(()=>expect(result.current.config).not.toBeNull());await act(()=>result.current.connect({} as never));await act(()=>result.current.importPackage('ciphertext','password'));unmount();expect([...secret]).toEqual(new Array(32).fill(0));expect([...salt]).toEqual(new Array(32).fill(0));});
test('address override cannot replace the deployment receipt contract',async()=>{vi.stubEnv('VITE_CONTRACT_ADDRESS','d'.repeat(64));try{const {result}=renderHook(()=>useMidnight());await waitFor(()=>expect(result.current.error).toMatch(/configuration/i));expect(result.current.config).toBeNull();expect(mocks.connect).not.toHaveBeenCalled();}finally{vi.unstubAllEnvs();}});
test('disconnect suppresses late commit results',async()=>{let resolve!:(value:unknown)=>void;mocks.run.mockReturnValue(new Promise(r=>{resolve=r;}));mocks.decrypt.mockResolvedValue({scope:{},state:{secret:new Uint8Array(32).fill(9),salt:new Uint8Array(32).fill(8),rank:7n}});const {result}=renderHook(()=>useMidnight());await waitFor(()=>expect(result.current.config).not.toBeNull());await act(()=>result.current.connect({} as never));await act(()=>result.current.importPackage('ciphertext','password'));let committing!:Promise<void>;act(()=>{committing=result.current.commit(7n);});await waitFor(()=>expect(mocks.run).toHaveBeenCalled());act(()=>result.current.disconnect());await act(async()=>{resolve({status:'confirmed',txId:'a'.repeat(64)});await committing;});expect(result.current.result).toBeNull();expect(result.current.privateReady).toBe(false);expect(result.current.stage).toBeNull();});
test('disconnect during post-confirmation refresh suppresses stale state updates',async()=>{let finishRead!:(value:unknown)=>void;mocks.read.mockResolvedValueOnce(publicState).mockResolvedValueOnce(publicState).mockImplementationOnce(()=>new Promise(r=>{finishRead=r;}));mocks.run.mockResolvedValue({status:'confirmed',txId:'a'.repeat(64)});mocks.decrypt.mockResolvedValue({scope:{},state:{secret:new Uint8Array(32).fill(9),salt:new Uint8Array(32).fill(8),rank:7n}});const {result}=renderHook(()=>useMidnight());await waitFor(()=>expect(result.current.publicState).toEqual(publicState));await act(()=>result.current.connect({} as never));await act(()=>result.current.importPackage('ciphertext','password'));let committing!:Promise<void>;act(()=>{committing=result.current.commit(7n);});await waitFor(()=>expect(finishRead).toBeTypeOf('function'));act(()=>result.current.disconnect());await act(async()=>{finishRead({phase:1,round:1n});await committing;});expect(result.current.publicState).toEqual(publicState);});
