import { useState } from 'react';
import { useMidnight } from './useMidnight.ts';
import { WalletConnect } from './components/WalletConnect.tsx';
import { PrivatePackageForm } from './components/PrivatePackageForm.tsx';
import { CircuitCall } from './components/CircuitCall.tsx';
import { contractExplorer } from './config.ts';

const phaseLabels=['Empty','Committed','Challenged','Resolved'];
function clickSound() {
  try {
    const context=new AudioContext(), oscillator=context.createOscillator(), gain=context.createGain();
    oscillator.type='sine'; oscillator.frequency.value=440; gain.gain.setValueAtTime(0.025,context.currentTime);
    gain.gain.exponentialRampToValueAtTime(0.001,context.currentTime+0.09);
    oscillator.connect(gain);gain.connect(context.destination);oscillator.start();oscillator.stop(context.currentTime+0.1);
    oscillator.onended=()=>{void context.close();};
  } catch { /* Sound is optional; it cannot affect a transaction. */ }
}
export default function App(){
  const app=useMidnight(),[claim,setClaim]=useState(1),[sound,setSound]=useState(false);
  const confirmed=app.result?.status==='confirmed'?app.result:undefined;
  const txId=confirmed?.txId ?? app.pending?.txId;
  const canCommit=Boolean(app.config&&app.wallet.status==='connected'&&app.privateReady&&app.publicState?.phase===0&&!app.busy&&!app.pending&&!confirmed);
  const reason=!app.config?'Checking deployment configuration…':app.pending?'Check the existing transaction before taking another action.':app.publicState&&app.publicState.phase!==0?'This round already has a commitment. Its public result is available below.':!app.privateReady?'Connect Lace and unlock the player package to continue.':undefined;
  return <>
    <a className="skip-link" href="#demo">Skip to private action</a>
    <header className="site-header wrap"><a className="brand" href="#top" aria-label="Cat Bluff home"><span className="brand-mark" aria-hidden="true">♣</span>cat bluff<span className="brand-period">.</span></a><nav aria-label="Main"><a href="#guide">How it works</a><a href="https://github.com/AyushPaul26/cat-bluff-midnight" target="_blank" rel="noreferrer">Source ↗</a><span className="network-badge"><span/>Preprod</span></nav></header>
    <main id="top" className="wrap">
      <section className="hero" aria-labelledby="hero-heading"><div className="hero-copy"><p className="eyebrow">THE PRIVATE CARD CLUB / MIDNIGHT</p><h1 id="hero-heading">A little mystery.<br/><em>A lot of cattitude.</em></h1><p className="hero-intro">Make your claim. Keep your card.<br/>A tiny taste of a bluffing game where secrets belong to the player.</p><div className="hero-actions"><a className="button primary" href="#demo">Try the private action <span aria-hidden="true">↘</span></a><span className="handwritten">poker face optional</span></div><p className="hero-note"><span aria-hidden="true">✳</span> Built on Midnight · Free test network</p></div><figure className="hero-art"><img src="/cat-club.svg" width="560" height="430" alt="Two illustrated cats guarding decorative playing cards at the Cat Bluff card club"/><figcaption>Club artwork · independent of the private input</figcaption></figure></section>
      <div className="demo-heading" id="demo"><div><p className="eyebrow">LEVEL 2 / PRIVATE ACTION DEMO</p><h2>Big secrets. Small first step.</h2></div><button className="sound-toggle" aria-pressed={sound} aria-label={sound?'Mute sound':'Enable sound'} onClick={()=>{if(!sound)clickSound();setSound(!sound);}}><span aria-hidden="true">{sound?'♪':'♩'}</span> Sound {sound?'on':'off'}</button></div>
      <p className="scope-note">One round. One private action. This prototype proves an authorized commitment to a valid hidden rank. The full multiplayer card game comes later.</p>
      {app.error && <div className="error global-error" role="alert">{app.error}<button className="text-button" disabled={app.busy} onClick={()=>{void app.refresh();}}>Refresh public state</button></div>}
      <div className="demo-grid">
        <WalletConnect wallet={app.wallet} choices={app.choices} onConnect={choice=>{void app.connect(choice);}} onDisconnect={app.disconnect} onGetFaucetAddress={app.getFaucetAddress} busy={app.busy}/>
        <PrivatePackageForm enabled={app.wallet.status==='connected'&&!app.busy} ready={app.privateReady} onImport={app.importPackage}/>
        <CircuitCall canCommit={canCommit} busy={app.busy} claim={claim} onClaim={setClaim} onCommit={()=>{if(sound)clickSound();void app.commit(BigInt(claim));}} reason={reason} stage={app.stage??undefined} txId={txId} confirmation={confirmed} onRecheck={app.pending?()=>{void app.recheck();}:undefined}/>
      </div>
      <section className="public-board" aria-labelledby="public-heading"><div><p className="eyebrow">READ FROM PREPROD</p><h3 id="public-heading">On the table</h3></div><div className="public-stat"><span>Round</span><strong>{app.publicState?.round.toString()??'—'}</strong></div><div className="public-stat"><span>Public phase</span><strong>{app.publicLoading?'Checking…':app.publicState?phaseLabels[app.publicState.phase]:'Not verified'}</strong></div><div className="public-stat"><span>Claimed rank</span><strong>{app.publicState&&app.publicState.phase!==0?['A','2','3','4','5','6','7','8','9','10','J','Q','K'][Number(app.publicState.claimedRank)-1]:'—'}</strong></div><button className="text-button" disabled={app.publicLoading||app.busy} onClick={()=>{void app.refresh();}}>Refresh ↻</button></section>
      <section className="privacy-grid" aria-label="Privacy explanation"><article><span className="privacy-icon" aria-hidden="true">↗</span><h3>What goes on the table</h3><p>Your claim, a randomized card commitment, the round, the public phase and transaction metadata. These are visible on Preprod.</p></article><article><span className="privacy-icon" aria-hidden="true">✳</span><h3>What stays in your paw</h3><p>The actual rank, random salt and player role secret stay out of the public commitment. Your browser, Lace and your local prover process private inputs.</p></article><article><span className="privacy-icon" aria-hidden="true">♣</span><h3>Bluffing is still the point</h3><p>A valid hidden rank needn’t match your public claim. This proof establishes neither fair dealing nor ownership of a dealt card. Resolution later reveals the rank deliberately.</p></article></section>
      <section id="guide" className="guide" aria-labelledby="guide-heading"><div><p className="eyebrow">FIRST TIME AT THE TABLE?</p><h2 id="guide-heading">Get your paws ready.</h2><p className="muted">A hosted page still needs your own wallet and prover.</p></div><ol><li><strong>Open Lace on Preprod</strong><p>Use a supported browser with Lace’s compatible Midnight connector. Unlock your wallet and use free test resources only.</p></li><li><strong>Start your local proof server</strong><p>Run the pinned 8.1.0 server on loopback and configure Lace to use it. This demo checks the wallet’s reported proving endpoint before an action.</p></li><li><strong>Unlock the operator’s package</strong><p>Export the original player capability using the local project tool. Import the encrypted file privately; it stays off the website’s server.</p></li><li><strong>Make a claim, then verify</strong><p>Choose a public rank, commit, and review Lace’s request yourself. Confirmation requires both successful indexed status and the matching public commitment.</p></li></ol><a className="text-link" href="https://github.com/AyushPaul26/cat-bluff-midnight/blob/main/docs/DEPLOYMENT.md" target="_blank" rel="noreferrer">Setup and recovery instructions ↗</a></section>
      <details className="technical"><summary>Public configuration &amp; prototype limits</summary><div className="technical-content"><p>Network: Midnight Preprod. Proof path: wallet-mediated, user-local native prover. Browser-WASM proving is not established.</p>{app.config?<><p>Contract address</p><a className="address" href={contractExplorer(app.config.contractAddress)} target="_blank" rel="noreferrer">{app.config.contractAddress} ↗</a><p>Indexer: <code>{app.config.indexer}</code></p><p>Expected local prover: <code>{app.config.proverServer}</code></p></>:<p>Deployment configuration has not been verified.</p>}<p>This contract has one round and fixed secret-based roles. A connected wallet pays for the action; it does not grant player authorization. There is no dealing, matchmaking, reward, wager or multiplayer service. After committing, keep the original encrypted package to allow future resolution.</p><p>Disconnect releases this app’s private session. It does not cancel a transaction already submitted or revoke saved Lace permissions. Pending transaction metadata is public and retained locally for reconciliation.</p></div></details>
    </main><footer className="wrap"><span className="brand">cat bluff.</span><p>Keep your cards close. Keep the game honest about its limits.</p><span>Made for the Midnight moonshot</span></footer>
  </>;
}
