import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { access, readFile, writeFile } from 'node:fs/promises';
import { deployContract } from '@midnight-ntwrk/midnight-js-contracts';
import { ledger, pureCircuits } from '../managed/cat-bluff/contract/index.js';
import { buildWallet, loadSecrets } from './wallet.ts';
import { compiledContract, providersFor } from './providers.ts';
import { prepareFunds } from './funds.ts';

// Never serialize SDK result/error objects: they can contain private inputs.
async function main() {
  try { await access('.private/deploy-receipt.json'); throw new Error('A deployment receipt already exists; inspect it before redeploying.'); }
  catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error; }
  const saved = await loadSecrets();
  const client = await buildWallet(saved);
  try {
    const health = await fetch(`${client.env.proofServer}/health`, { signal: AbortSignal.timeout(10_000) });
    if (!health.ok) throw new Error('Local proof server health check failed');
    const providers = providersFor(client, saved);
    const context = new Uint8Array(Buffer.from(saved.context, 'hex'));
    const playerSecret = new Uint8Array(Buffer.from(saved.playerSecret, 'hex'));
    const player = pureCircuits.deriveRole(context, 1n, playerSecret);
    const challenger = pureCircuits.deriveRole(context, 2n, new Uint8Array(Buffer.from(saved.challengerSecret, 'hex')));
    await prepareFunds(client);
    console.log('Deploying custom Cat Bluff to Preprod; waiting for confirmation.');
    const deployed = await deployContract(providers, {
      compiledContract,
      privateStateId: 'cat-bluff-player',
      initialPrivateState: { secret: playerSecret, rank: BigInt(saved.rank), salt: new Uint8Array(Buffer.from(saved.salt, 'hex')) },
      args: [context, player, challenger],
    });
    const publicTx = deployed.deployTxData.public;
    assert.equal(publicTx.status, 'SucceedEntirely');
    const receipt = {
      network: 'preprod', contractAddress: publicTx.contractAddress,
      txId: publicTx.txId, txHash: publicTx.txHash, blockHash: publicTx.blockHash,
      blockHeight: publicTx.blockHeight, status: publicTx.status,
    };
    await writeFile('.private/deploy-receipt.json', JSON.stringify(receipt, null, 2), { flag: 'wx' });
    const chain = await providers.publicDataProvider.queryContractState(receipt.contractAddress);
    assert.ok(chain, 'Indexer did not return the deployed contract');
    const state = ledger(chain.data);
    assert.deepEqual(state.gameContext, context);
    assert.deepEqual(state.player, player);
    assert.deepEqual(state.challenger, challenger);
    assert.equal(state.phase, 0);
    assert.equal(state.round, 1n);
    const artifacts: Record<string, string> = {};
    for (const circuit of ['commit', 'challenge', 'resolve'] as const) {
      const key = await providers.zkConfigProvider.getVerifierKey(circuit);
      assert.deepEqual(chain.operation(circuit)?.verifierKey, new Uint8Array(key), `On-chain ${circuit} verifier mismatch`);
      artifacts[circuit] = createHash('sha256').update(key).digest('hex');
    }
    const evidence = {
      ...receipt, verifiedAt: new Date().toISOString(), indexer: client.env.indexer,
      sourceSha256: createHash('sha256').update(await readFile('contracts/cat-bluff.compact')).digest('hex'),
      verifierSha256: artifacts, verifiedInitialPhase: 'Empty',
    };
    await writeFile('docs/evidence/deployment.json', JSON.stringify(evidence, null, 2) + '\n');
    console.log('CONFIRMED: custom Cat Bluff ledger and all three verifier keys match the indexer.');
    console.log(JSON.stringify(evidence, null, 2));
  } finally { await client.wallet.stop(); }
}

main().catch(error => {
  // Messages generated by this application are safe. SDK errors may include
  // transaction/witness material, so expose only the error class externally.
  const name = error instanceof Error ? error.name : 'UnknownError';
  console.error(`Deployment did not finish (${name}). No confirmed deployment is claimed.`);
  process.exitCode = 1;
});
